### ISSUE TITLE
Won't Index Library

### ISSUE THREAD

**Issue by llewellynathan** [romannurik/Sketch-Stickers#7]
I've followed the instructions to create a sticker sheet using the syntax in the Wiki but when I run the Stickers plugin it tells me that none of my Sketch libraries have stickers yet. The file I'm referencing is a Sketch library file and it is enabled in my preferences. 

I'm on the latest version of Sketch and the latest version of the plugin.

**Comment by romannurik** [comment]
Hmm odd. Mind sending the library my way? Either here or privately to roman AT nurik DOT net

**Comment by romannurik** [comment]
Also does the example library index correctly for you?

**Comment by llewellynathan** [comment]
The example library does work for me. Any other library will not. No other library will work.

Nate Llewellyn

**Comment by romannurik** [comment]
Hey Nate! I took a look at the sample you sent over and I found that the problem was you had special characters in your section IDs (e.g. `@Buttons&Links`, you can't use ampersands so it should be something like `@ButtonsAndLinks`). These IDs aren't really visible in the Stickers plugin so they dont have to be perfect. Once I removed the ampersands it started indexing fine for me. I'll update the Wiki to note this requirement. Hope that helps!

**Comment by llewellynathan** [comment]
Thanks so Much!

Nate Llewellyn
